mergeSort:
	g++ -std=c++11 -o mergeSort mergeSort.cpp util.cpp sort.cpp

insertSort:
	g++ -std=c++11 -o insertSort insertSort.cpp util.cpp sort.cpp

mergeTime:
	g++ -o mergeTime mergeSortTime.cpp sort.cpp

insertTime:
	g++ -o insertTime insertSortTime.cpp sort.cpp
